Product Inventory system service
SetMyDream/E-commerce pull request #3
Opened 2021-02-26 13:25 UTC by SetMyDream

Added Product model, form, DAO and service layer, routes and view.

2021-02-26 16:34 UTC, gemelen requested changes

2021-02-26 16:34 UTC, gemelen commented on product_inventory_service/build.sbt
> +    scalaVersion := "2.13.4",
Scala version №1

2021-02-26 16:34 UTC, gemelen commented on product_inventory_service/build.sbt
> +scalaVersion := "2.12.3"
Scala version №2.
Please decide which one to use and set it once

2021-02-26 16:34 UTC, gemelen commented on product_inventory_service/plugins.sbt
> +// For checkstyle
Please use `addSbtPlugin("com.beautiful-scala" % "sbt-scalastyle" % "1.5.0")` instead.

2021-02-26 16:34 UTC, gemelen commented on product_inventory_service/plugins.sbt
> +addSbtPlugin("com.lucidchart" % "sbt-scalafmt" % "1.16")
WTF is this?
`addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.4.2")` is official one

2021-02-26 16:34 UTC, gemelen commented on product_inventory_service/project/plugins.sbt
> +// The Play plugin
You don't need this file here.

2021-02-26 16:34 UTC, gemelen commented on product_inventory_service/src/main/scala/conf/Application.conf
> +play.filters.disabled+=play.filters.csrf.CSRFFilter
I believe it should be named `application.conf`

2021-03-01 11:12 UTC, gemelen approved these changes

2021-03-03 10:55 UTC, me-anton approved these changes

2021-03-05 10:53 UTC, merged